//! MomoBako 内建 Mutsuki 长任务 runner 组合入口。

#[cfg(test)]
mod cancellation_tests;
mod operations;
mod protocols;
mod task_runtime;

pub use protocols::{
    PROTOCOL_ARCHIVE_IMPORT, PROTOCOL_EAGLE_IMPORT, PROTOCOL_ENTRY_COPY, PROTOCOL_ENTRY_DELETE,
    PROTOCOL_ENTRY_IMPORT, PROTOCOL_ENTRY_MOVE, PROTOCOL_PLAYBACK_PREPARE,
    PROTOCOL_PLAYLIST_DOWNLOAD, PROTOCOL_REPOSITORY_ACTION_RUN, PROTOCOL_REPOSITORY_ATTACH,
    PROTOCOL_REPOSITORY_CREATE, PROTOCOL_REPOSITORY_EXPORT, PROTOCOL_REPOSITORY_IMPORT,
    PROTOCOL_REPOSITORY_RELOCATE, PROTOCOL_REPOSITORY_SYNC, PROTOCOL_THUMBNAIL_REQUEST,
};
pub use task_runtime::MomoTaskRuntime;
