[package]
name = "momobako-nana"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
publish = false

[dependencies]
nana-ui = { git = "https://github.com/sena-nana/NanaUI.git", rev = "ee94106746b13f356af17586ed5e35ed78f9eb40", features = ["hosted", "bundled-fonts", "components"] }
nana-ui-platform = { git = "https://github.com/sena-nana/NanaUI.git", rev = "ee94106746b13f356af17586ed5e35ed78f9eb40", features = ["clipboard"] }

[dev-dependencies]
serde_json = "1"
nana-ui-devtools = { git = "https://github.com/sena-nana/NanaUI.git", rev = "ee94106746b13f356af17586ed5e35ed78f9eb40", features = ["runtime-agent"] }

[[bin]]
name = "momobako-nana"
path = "src/main.rs"
